### ISSUE TITLE
Rename project to avoid confusion

### ISSUE THREAD

**Issue by TheAssassin** [AppImageCrafters/AppImageBuilder#2]
The project https://github.com/TheAssassin/appimagecraft has existed already before this project was born. Please rename your project in order to avoid confusion.

**Comment by azubieta** [comment]
The Github project was renamed. The names in the code will be changed latter. Yet if at some point you decide to discontinue the project  please let us know.

**Comment by antony-jr** [comment]
Do we really need to rename??? Project with same name exists and it's open source after all. For example https://github.com/meefik/linuxdeploy and https://github.com/linuxdeploy/linuxdeploy exists, is it fair to change the name of @TheAssassin's linuxdeploy to avoid confusions with https://github.com/meefik/linuxdeploy??

**Comment by azubieta** [comment]
@antony-jr your rationale seems valid to me. To be honest, I agreed on changing the project name to avoid conflict with @TheAssassin. In the end we all seek the same goal, making a better package distribution experience.
